dag_name: dag17
dag_tasks:
  - task_name: task1
    task_path: task1.sql
  - task_name: task2
    task_path: task2.sql
    task_dependencies:
        - task1
  - task_name: task3
    task_path: task3.sql
    task_dependencies:
        - task1
        - task2
dag_schedule: 0 0 * * *
