dag_name: dag17
dag_tasks:
  - name: task1
    path: task1.sql
  - name: task2
    path: task2.sql
    dependencies:
        - task1
  - name: task3
    path: task3.sql
    dependencies:
        - task1
        - task2
dag_schedule: 0 0 * * *
